import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  late Map<String, String> _localizedStrings;

  static const Map<String, Map<String, String>> _translations = {
    'en': {
      'settings': 'Settings',
      'language': 'Language',
      'choose_language': 'Choose Language',
      'english': 'English',
      'sinhala': 'Sinhala',
      'theme': 'Theme',
      'dark_mode': 'Dark Mode',
      'light_mode': 'Light Mode',
      'appearance': 'Appearance',
      'appearance_subtitle': 'Use system, light, or dark mode',
      'system': 'System',
      'light': 'Light',
      'dark': 'Dark',
      'receipt_footer': 'Receipt footer',
      'printing_options': 'Printing options',
      'printing_subtitle': 'Paper size, copies and automatic printing',
      'security': 'Security',
      'security_subtitle': 'Demo mode with local protected session',
      'store_management': 'Store Management',
      'store_subtitle': 'Profile, receipt identity and logo',
      'profile': 'Profile',
      'merchant_admin': 'Merchant administrator',
      'terminal': 'Terminal',
      'terminal_subtitle': 'Mobile POS terminal active',
      'management': 'Management',
      'reports': 'Reports',
      'products': 'Products',
      'stocks': 'Stocks',
      'categories': 'Categories',
      'brands': 'Brands',
      'units': 'Units',
      'suppliers': 'Suppliers',
      'product_suppliers': 'Product Suppliers',
      'stock_movements': 'Stock Movements',
      'batches': 'Batches',
      'images': 'Images',
      'taxes': 'Taxes',
      'discounts': 'Discounts',
      'variants': 'Variants',
      'customers': 'Customers',
      'credit_ledger': 'Credit Ledger',
      'branches': 'Branches',
      'roles': 'Roles',
      'users': 'Users',
      'pos_sales': 'POS Sales',
      'pos_management': 'POS Management',
      'management_subtitle': 'Reports, stock, cashiers and credit',
      'live_api': 'Live API',
      'dashboard': 'Dashboard',
      'net_sales': 'Net Sales',
      'collected': 'Collected',
      'credit_due': 'Credit Due',
      'items_sold': 'Items Sold',
      'quick_actions': 'Quick Actions',
      'open_pos': 'Open POS',
      'sales_overview': 'Sales Overview',
      'cashier_sales_credit': 'Cashier Sales & Credit',
      'recent_sales_list': 'Recent Sales',
      'no_cashier_sales': 'No cashier sales found yet.',
      'no_recent_sales': 'No recent sales found yet.',
      'good_day': 'Good day',
      'sales_target_progress': 'Today sales target progress',
      'today_sales': 'today sales',
      'last_7_days': 'Last 7 Days Sales',
      'no_chart_data': 'No chart data',
      'logout': 'Logout',
      'products_subtitle': 'Manage SKU, barcode, price, stock, tax and status.',
      'stocks_subtitle': 'View available stock, minimum levels and category.',
      'categories_subtitle': 'Group products by grocery, dairy, frozen and beverage.',
      'brands_subtitle': 'Manage product brand names and status.',
      'units_subtitle': 'Configure pcs, kg, litre, pack and box units.',
      'suppliers_subtitle': 'Supplier contact, phone, email and address.',
      'product_suppliers_subtitle': 'Connect products with suppliers and supplier prices.',
      'stock_movements_subtitle': 'Track purchase, sale, adjustment and returns.',
      'batches_subtitle': 'Batch number, purchase price, selling price and expiry.',
      'images_subtitle': 'Attach product image path or upload image.',
      'taxes_subtitle': 'Manage tax name, percentage and status.',
      'discounts_subtitle': 'Fixed or percentage discount with date range.',
      'variants_subtitle': 'Variant barcode, cost, selling price and stock.',
      'customers_subtitle': 'Credit limit, balance, available credit and status.',
      'credit_ledger_subtitle': 'Credit sale, payment and adjustment ledger.',
      'branches_subtitle': 'Branch name, code, contact details and status.',
      'roles_subtitle': 'Backend roles used by cashiers, admins and managers.',
      'users_subtitle': 'View authenticated backend users and cashier accounts.',
      'pos_sales_subtitle': 'Create sales and update order/payment status.',
      'reports_subtitle': 'Sales, cashiers, products, items, inventory, payments, tax and credit.',
      'settings_subtitle': 'Payment methods, discount rules and receipt settings.',
      'rows': 'rows',
      'add': 'Add',
      'no': 'No',
      'found': 'found',
      'pull_to_refresh_or_add': 'Pull to refresh or add a new record.',
      'save_settings': 'Save settings',
      'edit': 'Edit',
      'update': 'Update',
      'save': 'Save',
      'close': 'Close',
      'is_required_lower': 'is required',
      'name': 'Name',
      'product_code': 'Product Code',
      'short_name': 'Short Name',
      'phone': 'Phone',
      'email': 'Email',
      'login': 'Login',
      'sign_up': 'Sign Up',
      'mobile_number': 'MOBILE NUMBER',
      'password': 'PASSWORD',
      'forgot_password': 'Forgot Password?',
      'dont_have_account': "Don't have an account?",
      'already_have_account': 'Already have an account?',
      'welcome_back': 'Unlock your mobile checkout drawer',
      'login_success': 'Login successful',
      'login_failed': 'Login failed. Please try again.',
      'mobile_number_required': 'Mobile number is required',
      'valid_mobile_required': 'Enter a valid mobile number',
      'password_required': 'Password is required',
      'password_too_short': 'Password is too short',
      'remember_me': 'Remember me',
      'new_merchant': 'New merchant? ',
      'create_account': 'Create Account',
      'full_name': 'FULL NAME',
      'email_address': 'EMAIL ADDRESS',
      'terminal_password': 'TERMINAL PASSWORD',
      'confirm_password': 'CONFIRM PASSWORD',
      'already_registered': 'Already registered? ',
      'enter_full_name': 'Enter full name',
      'enter_valid_mobile': 'Enter valid mobile number',
      'enter_valid_email': 'Enter valid email',
      'use_6_chars': 'Use at least 6 characters',
      'passwords_dont_match': 'Passwords do not match',
      'account_ready': 'Account ready. Sign in to continue.',
      'search_products': 'Search products, SKU or barcode...',
      'all_categories': 'All Categories',
      'cart': 'Cart',
      'items': 'Items',
      'empty_cart': 'Your cart is empty',
      'subtotal': 'Subtotal',
      'discount': 'Discount',
      'tax': 'Tax',
      'total': 'Total',
      'checkout': 'Checkout',
      'clear_cart': 'Clear',
      'held_orders': 'Held Orders',
      'current_cart': 'Current Cart',
      'resume_cart': 'Resume Cart',
      'no_items_added': 'No items added',
      'remove_held_order': 'Remove held order',
      'remove_held_order_confirm': 'Remove this held order?',
      'order_held_success': 'Order held successfully',
      'no_held_orders': 'No held orders found',
      'retry': 'Retry',
      'cancel': 'Cancel',
      'remove': 'Remove',
      'payment': 'Payment',
      'select_payment_method': 'Select payment method',
      'cash': 'Cash',
      'card': 'Card',
      'credit': 'Credit',
      'wallet': 'Wallet',
      'amount_to_pay': 'Amount to Pay',
      'amount_paid': 'Amount Paid',
      'paid_now': 'Paid now',
      'paid': 'Paid',
      'credit_amount': 'Credit Amount',
      'available_credit': 'Available Credit',
      'due_days': 'Due Days',
      'select_customer': 'Select Customer',
      'add_customer': 'Add Customer',
      'credit_customer': 'Credit customer',
      'quick_add_customer': 'Quick add customer',
      'manage': 'Manage',
      'order_summary': 'Order Summary',
      'this_sale_credit': 'This sale credit',
      'pay': 'Pay',
      'total_payable': 'TOTAL PAYABLE',
      'hold': 'HOLD',
      'complete_sale': 'COMPLETE SALE',
      'select_items_to_continue': 'Select items to continue',
      'change': 'Change',
      'balance': 'Balance',
      'complete_payment': 'Complete Payment',
      'complete_credit': 'Complete Credit',
      'payment_success': 'Payment Successful',
      'receipt': 'Receipt',
      'print_receipt': 'Print Receipt',
      'done': 'Done',
      'sale_no': 'Sale No',
      'customer': 'Customer',
      'date': 'Date',
      'share': 'Share',
      'download': 'Download',
      'start_new_sale': 'Start New Sale',
      'sales_receipt': 'Sales Receipt',
      'total_caps': 'TOTAL',
      'enter_weight': 'Enter weight in',
      'add_to_cart': 'ADD TO CART',
      'clear': 'CLEAR',
      'insufficient_stock': 'Insufficient stock. Max available',
      'store_profile': 'Store Profile',
      'store_name': 'Store Name',
      'legal_name': 'Legal Name',
      'address': 'Address',
      'city': 'City',
      'tax_number': 'Tax Number',
      'currency': 'Currency',
      'save_profile': 'Save Store Profile',
      'upload_logo': 'Upload Logo',
      'store_details': 'Store Details',
      'contact_receipt': 'Contact And Receipt',
      'store_logo': 'Store Logo',
      'active': 'Active',
      'save_store': 'Save Store',
      'create_store': 'Create Store',
      'upload': 'Upload',
      'sku': 'SKU',
      'stock': 'Stock',
      'each': 'each',
      'store_profile_saved': 'Store profile saved',
      'store_logo_uploaded': 'Store logo uploaded',
      'required_field': 'Field is required',
      'connection_type': 'Connection Type',
      'bluetooth': 'Bluetooth',
      'usb': 'USB',
      'paper_size': 'Paper Size',
      'automatic_printing': 'Automatic Printing',
      'auto_print_subtitle': 'Automatically print receipt after payment',
      'available_devices': 'Available Devices',
      'no_devices_found': 'No devices found. Tap refresh to scan.',
      'print_test_page': 'Print Test Page',
      'connect_printer_first': 'Connect to a printer first to print test page',
      'bluetooth_permission_required': 'Bluetooth and Location permissions are required for printer discovery',
      'onboarding_title_1': 'Fast & Easy POS',
      'onboarding_subtitle_1': 'Complete sales in seconds with our intuitive terminal designed for speed.',
      'onboarding_title_2': 'Inventory Control',
      'onboarding_subtitle_2': 'Keep track of stock levels, movement history, and low-stock alerts automatically.',
      'onboarding_title_3': 'Smart Analytics',
      'onboarding_subtitle_3': 'Gain insights into your business performance with real-time reports and charts.',
      'skip': 'Skip',
      'next': 'Next',
      'get_started': 'Get Started',
      'splash_tagline': 'Smart Business, Simplified Payments',
      'initializing_security': 'Initializing security node...',
      'connecting_gateway': 'Connecting terminal gateway...',
      'decrypting_token': 'Decrypting merchant token...',
      'terminal_authorized': 'Terminal Authorized!',
      'secure_connection': 'PCI-DSS COMPLIANT • SECURE CONNECTION',
    },
    'si': {
      'settings': 'සැකසුම්',
      'language': 'භාෂාව',
      'choose_language': 'භාෂාව තෝරන්න',
      'english': 'ඉංග්‍රීසි',
      'sinhala': 'සිංහල',
      'theme': 'තේමාව',
      'dark_mode': 'අඳුරු මාදිලිය',
      'light_mode': 'ආලෝක මාදිලිය',
      'appearance': 'පෙනුම',
      'appearance_subtitle': 'පද්ධතිය, ආලෝකය හෝ අඳුරු මාදිලිය භාවිතා කරන්න',
      'system': 'පද්ධතිය',
      'light': 'ආලෝකය',
      'dark': 'අඳුරු',
      'receipt_footer': 'රිසිට්පත් පාදකය',
      'printing_options': 'මුද්‍රණ විකල්ප',
      'printing_subtitle': 'කඩදාසි ප්‍රමාණය, පිටපත් සහ ස්වයංක්‍රීය මුද්‍රණය',
      'security': 'ආරක්ෂාව',
      'security_subtitle': 'දේශීය ආරක්ෂිත සැසිය සමඟ නිරූපණ මාදිලිය',
      'store_management': 'වෙළඳසැල් කළමනාකරණය',
      'store_subtitle': 'පැතිකඩ, රිසිට්පත් අනන්‍යතාවය සහ ලාංඡනය',
      'profile': 'පැතිකඩ',
      'merchant_admin': 'වෙළඳ පරිපාලක',
      'terminal': 'පර්යන්තය',
      'terminal_subtitle': 'ජංගම POS පර්යන්තය සක්‍රීයයි',
      'management': 'කළමනාකරණය',
      'reports': 'වාර්තා',
      'products': 'නිෂ්පාදන',
      'stocks': 'තොග',
      'categories': 'ප්‍රවර්ග',
      'brands': 'වෙළඳ නාම',
      'units': 'ඒකක',
      'suppliers': 'සැපයුම්කරුවන්',
      'product_suppliers': 'නිෂ්පාදන සැපයුම්කරුවන්',
      'stock_movements': 'තොග චලනයන්',
      'batches': 'කාණ්ඩ',
      'images': 'රූප',
      'taxes': 'බදු',
      'discounts': 'වට්ටම්',
      'variants': 'ප්‍රභේද',
      'customers': 'ගනුදෙනුකරුවන්',
      'credit_ledger': 'ණය ලෙජරය',
      'branches': 'ශාඛා',
      'roles': 'භූමිකාවන්',
      'users': 'පරිශීලකයන්',
      'pos_sales': 'POS අලෙවිය',
      'pos_management': 'POS කළමනාකරණය',
      'management_subtitle': 'වාර්තා, තොග, අයකැමි සහ ණය',
      'live_api': 'සජීවී API',
      'dashboard': 'පුවරුව',
      'net_sales': 'ශුද්ධ අලෙවිය',
      'collected': 'එකතු කරන ලද',
      'credit_due': 'හිඟ ණය',
      'items_sold': 'විකුණුම් භාණ්ඩ',
      'quick_actions': 'ඉක්මන් ක්‍රියා',
      'open_pos': 'POS විවෘත කරන්න',
      'sales_overview': 'අලෙවි දළ විශ්ලේෂණය',
      'cashier_sales_credit': 'අයකැමි අලෙවිය සහ ණය',
      'recent_sales_list': 'මෑත අලෙවිය',
      'no_cashier_sales': 'තවමත් අයකැමි අලෙවියක් හමු නොවීය.',
      'no_recent_sales': 'තවමත් මෑත අලෙවියක් හමු නොවීය.',
      'good_day': 'සුබ දවසක්',
      'sales_target_progress': 'අද අලෙවි ඉලක්කයේ ප්‍රගතිය',
      'today_sales': 'අද අලෙවිය',
      'last_7_days': 'පසුගිය දින 7 අලෙවිය',
      'no_chart_data': 'ප්‍රස්ථාර දත්ත නොමැත',
      'logout': 'ඉවත් වන්න',
      'products_subtitle': 'SKU, බාර්කෝඩ්, මිල, තොග, බදු සහ තත්ත්වය කළමනාකරණය කරන්න.',
      'stocks_subtitle': 'ලබාගත හැකි තොග, අවම මට්ටම් සහ ප්‍රවර්ග බලන්න.',
      'categories_subtitle': 'බඩු බාහිරාදිය, කිරි නිෂ්පාදන, ශීත කළ සහ පාන වර්ග අනුව නිෂ්පාදන සමූහගත කරන්න.',
      'brands_subtitle': 'නිෂ්පාදන වෙළඳ නාම සහ තත්ත්වය කළමනාකරණය කරන්න.',
      'units_subtitle': 'pcs, kg, ලීටර්, පැකට් සහ පෙට්ටි ඒකක වින්යාස කරන්න.',
      'suppliers_subtitle': 'සැපයුම්කරු සම්බන්ධතා, දුරකථන, විද්යුත් තැපෑල සහ ලිපිනය.',
      'product_suppliers_subtitle': 'නිෂ්පාදන සැපයුම්කරුවන් සහ සැපයුම්කරුගේ මිල සමඟ සම්බන්ධ කරන්න.',
      'stock_movements_subtitle': 'මිලදී ගැනීම්, අලෙවිය, ගැලපීම් සහ ප්රතිලාභ නිරීක්ෂණය කරන්න.',
      'batches_subtitle': 'කාණ්ඩ අංකය, මිලදී ගැනීමේ මිල, විකුණුම් මිල සහ කල් ඉකුත්වීම.',
      'images_subtitle': 'නිෂ්පාදන රූප පථය අමුණන්න හෝ රූපයක් උඩුගත කරන්න.',
      'taxes_subtitle': 'බදු නාමය, ප්රතිශතය සහ තත්ත්වය කළමනාකරණය කරන්න.',
      'discounts_subtitle': 'දින පරාසය සහිත ස්ථාවර හෝ ප්රතිශත වට්ටම්.',
      'variants_subtitle': 'ප්රභේද බාර්කෝඩ්, පිරිවැය, විකුණුම් මිල සහ තොග.',
      'customers_subtitle': 'ණය සීමාව, ශේෂය, පවතින ණය සහ තත්ත්වය.',
      'credit_ledger_subtitle': 'ණය අලෙවිය, ගෙවීම් සහ ගැලපුම් ලෙජරය.',
      'branches_subtitle': 'ශාඛා නාමය, කේතය, සම්බන්ධතා විස්තර සහ තත්ත්වය.',
      'roles_subtitle': 'අයකැමියන්, පරිපාලකයින් සහ කළමනාකරුවන් විසින් භාවිතා කරනු ලබන පසුබිම් භූමිකාවන්.',
      'users_subtitle': 'සත්යාපිත පරිශීලකයින් සහ අයකැමි ගිණුම් බලන්න.',
      'pos_sales_subtitle': 'විකුණුම් සාදා ඇණවුම්/ගෙවීම් තත්ත්වය යාවත්කාලීන කරන්න.',
      'reports_subtitle': 'අලෙවිය, අයකැමියන්, නිෂ්පාදන, භාණ්ඩ, තොග, ගෙවීම්, බදු සහ ණය.',
      'settings_subtitle': 'ගෙවීම් ක්රම, වට්ටම් නීති සහ රිසිට්පත් සැකසුම්.',
      'rows': 'පේළි',
      'add': 'එක් කරන්න',
      'no': 'කිසිදු',
      'found': 'හමු නොවීය',
      'pull_to_refresh_or_add': 'නැවුම් කිරීමට අදින්න හෝ අලුත් එකක් එක් කරන්න.',
      'save_settings': 'සැකසුම් සුරකින්න',
      'edit': 'සංස්කරණය',
      'update': 'යාවත්කාලීන කරන්න',
      'save': 'සුරකින්න',
      'close': 'වසා දමන්න',
      'is_required_lower': 'අවශ්ය වේ',
      'name': 'නම',
      'product_code': 'නිෂ්පාදන කේතය',
      'short_name': 'කෙටි නම',
      'phone': 'දුරකථනය',
      'email': 'විද්යුත් තැපෑල',
      'login': 'ඇතුළු වන්න',
      'sign_up': 'ලියාපදිංචි වන්න',
      'mobile_number': 'ජංගම දුරකථන අංකය',
      'password': 'මුරපදය',
      'forgot_password': 'මුරපදය අමතකද?',
      'dont_have_account': 'ගිණුමක් නොමැතිද?',
      'already_have_account': 'දැනටමත් ගිණුමක් තිබේද?',
      'welcome_back': 'ඔබේ ජංගම විකුණුම් කවුළුව විවෘත කරන්න',
      'login_success': 'ඇතුළුවීම සාර්ථකයි',
      'login_failed': 'ඇතුළුවීම අසාර්ථකයි. නැවත උත්සාහ කරන්න.',
      'mobile_number_required': 'ජංගම දුරකථන අංකය අවශ්ය වේ',
      'valid_mobile_required': 'වලංගු ජංගම දුරකථන අංකයක් ඇතුළත් කරන්න',
      'password_required': 'මුරපදය අවශ්ය වේ',
      'password_too_short': 'මුරපදය කෙටි වැඩියි',
      'remember_me': 'මාව මතක තබා ගන්න',
      'new_merchant': 'නව වෙළෙන්දෙක්ද? ',
      'create_account': 'ගිණුමක් සාදන්න',
      'full_name': 'සම්පූර්ණ නම',
      'email_address': 'විද්යුත් තැපැල් ලිපිනය',
      'terminal_password': 'පර්යන්ත මුරපදය',
      'confirm_password': 'මුරපදය තහවුරු කරන්න',
      'already_registered': 'දැනටමත් ලියාපදිංචි වී තිබේද? ',
      'enter_full_name': 'සම්පූර්ණ නම ඇතුළත් කරන්න',
      'enter_valid_mobile': 'වලංගු ජංගම දුරකථන අංකයක් ඇතුළත් කරන්න',
      'enter_valid_email': 'වලංගු විද්යුත් තැපෑලක් ඇතුළත් කරන්න',
      'use_6_chars': 'අවම වශයෙන් අක්ෂර 6 ක් භාවිතා කරන්න',
      'passwords_dont_match': 'මුරපද නොගැලපේ',
      'account_ready': 'ගිණුම සූදානම්. ඉදිරියට යාමට ඇතුළු වන්න.',
      'search_products': 'නිෂ්පාදන, SKU හෝ බාර්කෝඩ් සොයන්න...',
      'all_categories': 'සියලුම ප්රවර්ග',
      'cart': 'කරත්තය',
      'items': 'භාණ්ඩ',
      'empty_cart': 'ඔබේ කරත්තය හිස්ය',
      'subtotal': 'එකතුව',
      'discount': 'වට්ටම්',
      'tax': 'බදු',
      'total': 'මුළු එකතුව',
      'checkout': 'ගෙවීම් කරන්න',
      'clear_cart': 'ඉවත් කරන්න',
      'held_orders': 'රඳවා ඇති ඇණවුම්',
      'current_cart': 'වත්මන් කරත්තය',
      'resume_cart': 'කරත්තය නැවත ආරම්භ කරන්න',
      'no_items_added': 'භාණ්ඩ කිසිවක් එකතු කර නැත',
      'remove_held_order': 'රඳවා ඇති ඇණවුම ඉවත් කරන්න',
      'remove_held_order_confirm': 'මෙම රඳවා ඇති ඇණවුම ඉවත් කරන්නද?',
      'order_held_success': 'ඇණවුම සාර්ථකව රඳවා ගන්නා ලදී',
      'no_held_orders': 'රඳවා ඇති ඇණවුම් හමු නොවීය',
      'retry': 'නැවත උත්සාහ කරන්න',
      'cancel': 'අවලංගු කරන්න',
      'remove': 'ඉවත් කරන්න',
      'payment': 'ගෙවීම',
      'select_payment_method': 'ගෙවීමේ ක්රමය තෝරන්න',
      'cash': 'මුදල්',
      'card': 'කාඩ්පත්',
      'credit': 'ණය',
      'wallet': 'පසුම්බිය',
      'amount_to_pay': 'ගෙවිය යුතු මුදල',
      'amount_paid': 'ගෙවූ මුදල',
      'paid_now': 'දැන් ගෙවූ මුදල',
      'paid': 'ගෙවන ලදී',
      'credit_amount': 'ණය මුදල',
      'available_credit': 'ලබාගත හැකි ණය',
      'due_days': 'හිඟ දින',
      'select_customer': 'ගනුදෙනුකරු තෝරන්න',
      'add_customer': 'ගනුදෙනුකරු එකතු කරන්න',
      'credit_customer': 'ණය ගනුදෙනුකරු',
      'quick_add_customer': 'ඉක්මනින් ගනුදෙනුකරු එකතු කරන්න',
      'manage': 'කළමනාකරණය',
      'order_summary': 'ඇණවුම් සාරාංශය',
      'this_sale_credit': 'මෙම අලෙවියේ ණය',
      'pay': 'ගෙවන්න',
      'total_payable': 'මුළු ගෙවිය යුතු මුදල',
      'hold': 'රඳවා තබා ගන්න',
      'complete_sale': 'විකුණුම් අවසන් කරන්න',
      'select_items_to_continue': 'ඉදිරියට යාමට භාණ්ඩ තෝරන්න',
      'change': 'ඉතිරි මුදල',
      'balance': 'හිඟය',
      'complete_payment': 'ගෙවීම අවසන් කරන්න',
      'complete_credit': 'ණය අවසන් කරන්න',
      'payment_success': 'ගෙවීම සාර්ථකයි',
      'receipt': 'රිසිට්පත',
      'print_receipt': 'රිසිට්පත මුද්රණය කරන්න',
      'done': 'අවසන්',
      'sale_no': 'විකුණුම් අංකය',
      'customer': 'ගනුදෙනුකරු',
      'date': 'දිනය',
      'share': 'බෙදාගන්න',
      'download': 'බාගත කරන්න',
      'start_new_sale': 'නව අලෙවියක් ආරම්භ කරන්න',
      'sales_receipt': 'අලෙවි රිසිට්පත',
      'total_caps': 'මුළු එකතුව',
      'enter_weight': 'බර ඇතුළත් කරන්න',
      'add_to_cart': 'කරත්තයට එක් කරන්න',
      'clear': 'මකන්න',
      'insufficient_stock': 'ප්රමාණවත් තොග නොමැත. උපරිම',
      'store_profile': 'වෙළඳසැල් පැතිකඩ',
      'store_name': 'වෙළඳසැල් නාමය',
      'legal_name': 'නීතිමය නාමය',
      'address': 'ලිපිනය',
      'city': 'නගරය',
      'tax_number': 'බදු අංකය',
      'currency': 'මුදල් වර්ගය',
      'save_profile': 'වෙළඳසැල් පැතිකඩ සුරකින්න',
      'upload_logo': 'ලාංඡනය උඩුගත කරන්න',
      'store_details': 'වෙළඳසැල් විස්තර',
      'contact_receipt': 'සම්බන්ධතා සහ රිසිට්පත්',
      'store_logo': 'වෙළඳසැල් ලාංඡනය',
      'active': 'සක්රීයයි',
      'save_store': 'වෙළඳසැල සුරකින්න',
      'create_store': 'වෙළඳසැල සාදන්න',
      'upload': 'උඩුගත කරන්න',
      'sku': 'SKU',
      'stock': 'තොගය',
      'each': 'බැගින්',
      'store_profile_saved': 'වෙළඳසැල් පැතිකඩ සුරකින ලදී',
      'store_logo_uploaded': 'වෙළඳසැල් ලාංඡනය උඩුගත කරන ලදී',
      'required_field': 'මෙම තීරුව අවශ්ය වේ',
      'connection_type': 'සම්බන්ධතා වර්ගය',
      'bluetooth': 'බ්ලූටූත්',
      'usb': 'USB',
      'paper_size': 'කඩදාසි ප්රමාණය',
      'automatic_printing': 'ස්වයංක්රීය මුද්රණය',
      'auto_print_subtitle': 'ගෙවීමෙන් පසු ස්වයංක්රීයව රිසිට්පත මුද්රණය කරන්න',
      'available_devices': 'ලබාගත හැකි උපාංග',
      'no_devices_found': 'උපාංග හමු නොවීය. ස්කෑන් කිරීමට නැවුම් කරන්න.',
      'print_test_page': 'පරීක්ෂණ පිටුව මුද්රණය කරන්න',
      'connect_printer_first': 'පරීක්ෂණ පිටුව මුද්රණය කිරීමට පළමුව මුද්රණ යන්ත්රයකට සම්බන්ධ වන්න',
      'bluetooth_permission_required': 'මුද්රණ යන්ත්ර සෙවීම සඳහා බ්ලූටූත් සහ ස්ථාන අවසර අවශ්ය වේ',
      'onboarding_title_1': 'වේගවත් සහ පහසු POS',
      'onboarding_subtitle_1': 'වේගය සඳහා නිර්මාණය කර ඇති අපගේ අවබෝධාත්මක පර්යන්තය සමඟ තත්පර කිහිපයකින් විකුණුම් සම්පූර්ණ කරන්න.',
      'onboarding_title_2': 'තොග පාලනය',
      'onboarding_subtitle_2': 'තොග මට්ටම්, චලන ඉතිහාසය සහ අඩු තොග ඇඟවීම් ස්වයංක්‍රීයව නිරීක්ෂණය කරන්න.',
      'onboarding_title_3': 'බුද්ධිමත් විශ්ලේෂණය',
      'onboarding_subtitle_3': 'තථ්‍ය කාලීන වාර්තා සහ ප්‍රස්ථාර සමඟ ඔබේ ව්‍යාපාරයේ ක්‍රියාකාරිත්වය පිළිබඳ අවබෝධයක් ලබා ගන්න.',
      'skip': 'මඟ හරින්න',
      'next': 'මීළඟ',
      'get_started': 'ආරම්භ කරන්න',
      'splash_tagline': 'බුද්ධිමත් ව්‍යාපාර, සරල කළ ගෙවීම්',
      'initializing_security': 'ආරක්ෂක නෝඩය ආරම්භ කරමින්...',
      'connecting_gateway': 'පර්යන්ත ද්වාරය සම්බන්ධ කරමින්...',
      'decrypting_token': 'වෙළඳ ටෝකනය විකේතනය කරමින්...',
      'terminal_authorized': 'පර්යන්තය අවසර දී ඇත!',
      'secure_connection': 'PCI-DSS අනුකූල • ආරක්ෂිත සම්බන්ධතාවය',
    },
  };

  void load() {
    _localizedStrings = _translations[locale.languageCode] ?? _translations['en']!;
  }

  String translate(String key) {
    return _localizedStrings[key] ?? key;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'si'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    AppLocalizations localizations = AppLocalizations(locale);
    localizations.load();
    return localizations;
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

extension TranslateExtension on BuildContext {
  String tr(String key) {
    return AppLocalizations.of(this)?.translate(key) ?? key;
  }
}
